language: go

matrix:
  include:
    - os: linux
      dist: xenial
      go: 1.9.x
    - os: linux
      dist: xenial
      go: 1.10.x
    - os: linux
      dist: xenial
      go: 1.11.x
    - os: linux
      dist: xenial
      go: 1.12.x
    - os: linux
      dist: bionic
      go: 1.13.x
    - os: linux
      dist: bionic
      go: 1.14.x
    - os: osx
      go: 1.12.x

script:
  - go install ./...
  - go test -v ./...
